name: Deploy to Render

on:
  push:
    branches: [ desplegament ]
  pull_request:
    branches: [ desplegament ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build web
      run: flutter build web --release --web-renderer html
      
    - name: Check build output
      run: ls -la build/web/

  # Render will automatically deploy when changes are pushed to the main branch
  # No additional deployment step needed here as Render handles it automatically
